import os
import datetime

def get_size_format(b, factor=1024, suffix="B"):
    for unit in ["", "K", "M", "G", "T", "P"]:
        if b < factor:
            return f"{b:.1f}{unit}{suffix}"
        b /= factor
    return f"{b:.1f}Y{suffix}"

def generate_index(root_dir):
    template = """
<!DOCTYPE html>
<html>
<head>
    <title>Index of {path}</title>
    <style>
        @font-face {{
            font-family: 'F1.8';
            src: url('https://cdn.jsdelivr.net/gh/lqy306/lqy306.github.io/fonts/F1.8-Regular.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
            font-display: swap;
        }}
        body {{ font-family: 'F1.8', 'JetBrains Mono', monospace; background-color: #0f0f0f; color: #e0e0e0; padding: 20px; }}
        h1 {{ border-bottom: 1px solid #333; padding-bottom: 10px; color: #1793d1; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ text-align: left; padding: 8px; border-bottom: 1px solid #222; }}
        th {{ color: #888; text-transform: uppercase; font-size: 0.8em; }}
        tr:hover {{ background-color: #1a1a1a; }}
        a {{ color: #1793d1; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .icon {{ margin-right: 10px; }}
        .footer {{ margin-top: 30px; font-size: 0.8em; color: #555; text-align: center; }}
    </style>
</head>
<body>
    <h1>Index of {path}</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Last Modified</th>
                <th>Size</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    <div class="footer">
        Generated by Auto-FTP Script | Arch Linux Spirit
    </div>
</body>
</html>
"""
    
    for root, dirs, files in os.walk(root_dir):
        # 排除隐藏文件夹和特定的系统文件夹
        dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['node_modules', '.github', 'fonts']]
        
        rel_path = os.path.relpath(root, root_dir)
        display_path = "/" if rel_path == "." else "/" + rel_path
        
        rows = []
        
        # 添加 "Parent Directory"
        if rel_path != ".":
            rows.append('<tr><td><a href="../">📁 ..</a></td><td>-</td><td>-</td></tr>')
        
        # 处理文件夹
        for d in sorted(dirs):
            d_path = os.path.join(root, d)
            mtime = datetime.datetime.fromtimestamp(os.path.getmtime(d_path)).strftime('%Y-%m-%d %H:%M:%S')
            rows.append(f'<tr><td><a href="{d}/">📁 {d}/</a></td><td>{mtime}</td><td>-</td></tr>')
            
        # 处理文件
        for f in sorted(files):
            if f in ['index.html', 'generate_index.py']: continue
            f_path = os.path.join(root, f)
            mtime = datetime.datetime.fromtimestamp(os.path.getmtime(f_path)).strftime('%Y-%m-%d %H:%M:%S')
            size = get_size_format(os.path.getsize(f_path))
            rows.append(f'<tr><td><a href="{f}">📄 {f}</a></td><td>{mtime}</td><td>{size}</td></tr>')
            
        index_content = template.format(path=display_path, rows="\n".join(rows))
        
        with open(os.path.join(root, "index.html"), "w") as f_out:
            f_out.write(index_content)

if __name__ == "__main__":
    # 假设资源存放在 resources 目录下
    resource_dir = "resources"
    if not os.path.exists(resource_dir):
        os.makedirs(resource_dir)
    generate_index(resource_dir)
