name: Auto Update FTP and Blog

on:
  push:
    paths:
      - 'resources/**'
      - 'post/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install markdown

      - name: Generate Index and Posts
        run: python generate_index.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resources/**/index.html post/**/index.html post/index.html
          git commit -m "Auto-update FTP index and Blog posts" || echo "No changes to commit"
          git push
